name: shell commands

on: 
  #push:
  schedule:
    - cron: "34 * * * *"
  pull_request:
    types: [closed, opened, assigned, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@master
      - name: list after checkout
        run: | 
          ls -a 
          pwd
      - name: print some variable
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
