name: shell commands

on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@master
      - name: list after checkout
        run: | 
          ls -a 
          pwd
