name: container
on: push
jobs:
  container_intialization:
    runs-on: ubuntu-latest
    container: 
      image: node:18-alpine3.16
    steps:
      - name: checking directory
        run: |
          node -v
          cd /etc/
          ls -ltr
