name: shell commands

on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "hello world"
      - name: multiline script
        run: |
          node -v
  run-powershell-command:
    runs-on: windows-latest
    steps:
      - name: create directory
        run: |
          mkdir my_file
          cd my_file
      - name: directory bash
        run: pwd 
        shell: bash
