name: matrix
on: push
jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16, 6]
        exclude:
          - os: windows-latest
            node-version: 16
          - os: windows-latest
            node-version: 6
          - os: ubuntu-latest
            node-version: 16
    runs-on: ${{matrix.os}}
    steps:
      - name: log node node-version
        run: node -v 
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: log node node-version
        run: node -v 
      
