name: matrix
on: push
jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: log node node-version
        run: node -v 
      - uses: actions/setup-node@v3
        with:
          os: windows-latest
      - name: log node node-version
        run: dir
