name: use of token
on: [push]
jobs:
  use-can-be:
    runs-on: ubuntu-latest
    steps:
      - name: push and pull 
        run: |
          pwd
          ls -a 
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_ACTOR"
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_token}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.name "pankaj"
          git config --global user.email "pankaj@gmail.com"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a 
          echo $RANDOM >> random.txt
          ls -a 
          git add -A 
          git commit -m "adding file"
          git push
